### ISSUE TITLE
Basic Enemy Ships

### ISSUE THREAD

**Issue by GraphicEdit** [GraphicEdit/BlueProject#14]
Enemie Ship

**Comment by GraphiteG** [comment]
![Enemy Placeholder](https://user-images.githubusercontent.com/62215985/77835413-ae944200-7122-11ea-82da-a630ff189ff0.png)

**Comment by GraphiteG** [comment]
![Enemy](https://user-images.githubusercontent.com/62215985/77836028-e7cfb080-7128-11ea-9fd0-8a61628a66e6.png)

**Comment by GraphiteG** [comment]
![Enemy 2](https://user-images.githubusercontent.com/62215985/77836477-d4bedf80-712c-11ea-991b-70bfb5deb2f8.png)
